# .github/workflows/docs.yml

name: Generate AI Documentation

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to the gh-pages branch

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate & Deploy Docs
        uses: jadenisaac2005/ai-docs-action@v1 # This calls the action
        with:
          api_key: ${{ secrets.AI_API_KEY }}
          api_endpoint: ${{ secrets.AI_API_ENDPOINT }}
          model_name: 'Salesforce/codet5-small' # Specify the model your endpoint uses
          source_dir: './src' # Optional: specify a subdirectory to document